theme: jekyll-theme-minimal
show_downloads: false
title: Codiply.com
# description:  
logo: images/profile.jpeg
google_analytics: UA-193741755-2
github:
  is_project_page: false
  is_user_page: false
